// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajyliamcyawyskaihgtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqeWxpYW1jeWF3eXNrYWloZ3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTIzNzMsImV4cCI6MjA2MDc4ODM3M30.uCHF0ohwPPTkxpzWFNAfQCZ985mbmlLGjVlaWmcdYlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);